### ISSUE TITLE
debian系统没有resolved.conf和ip转发的问题

### ISSUE THREAD

**Issue by kay-zhu** [mario-huang/sing-box-bypass-router-transparent-proxy-configuration#1]
感谢作者的付出！但有几个问题：
1、debian 12没有/etc/systemd/resolved.conf这个文件，不知道debian 12系统怎么设置？
2、我用ubuntu系统，需要打开ip转发才能使用，即：echo "net.ipv4.ip_forward = 1" >> /etc/sysctl.conf && sysctl -p
3、就算启用了以上，还是有些网站打不开，时有时无，或者报错DNS错误。

**Comment by mario-huang** [comment]
1、我没有debian可以测试，你可以尝试：
```bash
sudo micro /etc/systemd/resolved.conf.d/listen-on-all.conf
```
(micro可以换成你习惯的编辑工具，比如nano)
在新创建的文件中添加以下内容：
```
[Resolve]
DNSStubListenerExtra=0.0.0.0
DNSStubListenerExtra=::
```
保存并关闭文件。
重启systemd-resolved服务以应用更改：
```bash
sudo systemctl restart systemd-resolved
```
期待你的反馈

**Comment by mario-huang** [comment]
2、是的，你说的对

**Comment by mario-huang** [comment]
3、这个可能更多是singbox的配置问题，可以提供日志看看

**Comment by kay-zhu** [comment]
首先提示没有这个目录
[ Directory '/etc/systemd/resolved.conf.d' does not exist ]

然后写入后保存提示，也一样，因为没有目录
 [ Error writing /etc/systemd/resolved.conf.d/listen-on-all.conf: No such file or directory ]

**Comment by mario-huang** [comment]
那可以先创建这个目录：
sudo mkdir /etc/systemd/resolved.conf.d

**Comment by kay-zhu** [comment]
systemctl restart systemd-resolved
重启服务提示：
Failed to restart systemd-resolved.service: Unit systemd-resolved.service not found.

我看网上说debian12好像舍弃了resolved

**Comment by mario-huang** [comment]
看起来debian12没有使用systemd-resolved。
有两个方案：
1、安装systemd-resolved，那就可以按教程说的直接修改文件。但是可能需要调整系统，解决systemd-resolved和原来的DNS冲突问题。
2、DHCP的DNS解析那里，不指定使用旁路由的ip，使用119.29.29.29。

**Comment by kay-zhu** [comment]
我用的方式2，目前可用，路由器是mikrotik 5009 （ROS），指定了旁路由的DNS为119.29.29.29，但很慢，不知道是不是因为我是联通的原因
![Uploading 2024-09-21 114920.png…]()

**Comment by kay-zhu** [comment]
我用的方式2，目前可用，路由器是mikrotik 5009 （ROS），指定了旁路由的DNS为119.29.29.29，但很慢，不知道是不是因为我是联通的原因 
另外，一会儿网站又会打不开，提示DNS问题
![Uploading 2024-09-21 114920.png…]()

**Comment by mario-huang** [comment]
可以尝试多几个公共DNS。
https://dns.icoa.cn

**Comment by kay-zhu** [comment]
我的SB配置（1.10测试版）如下：
  "inbounds": [
    {
      "type": "tun",
      "tag": "tun-in",
      "interface_name": "tun0",
      "address": "172.19.0.1/30",
      "gso": true,
      "auto_route": true,
      "strict_route": false,
      "endpoint_independent_nat": true,
      "stack": "mixed",
      "sniff": true 
    }
  ],

**Comment by mario-huang** [comment]
可以试试我的
"inbounds": [
    {
      "type": "tun",
      "inet4_address": "172.19.0.1/30",
      "auto_route": true,
      "strict_route": false,
      "sniff": true,
      "sniff_override_destination": true
    }
  ],

**Comment by kay-zhu** [comment]
目前三种情况：
1、旁路由指向主路由的IP地址的话（默认不设置就是自动指向），会出现DNS泄露（https://ipleak.net/）
2、用你的方法（包括之前用ubuntu或现在Debian的DHCP的DNS解析那里，不指定使用旁路由的ip，使用119.29.29.29）会出现打开网站DNS无法解析的情况，或者时而可以时而不行。（网页出现：找不到 translate.google.com 的 DNS 地址… 现在正在诊断问题。）
3、另有一种方法可以正常使用，在SB配置入站中加入：
 {
      "type": "direct",
      "tag": "dns-in",
      "listen": "::",
      "listen_port": 53,
      "sniff": true
    }
然后route的rules加一条：
 {
        "inbound": "dns-in",
        "outbound": "dns-out"
      },

**Comment by kay-zhu** [comment]
> 可以试试我的 "inbounds": [ { "type": "tun", "inet4_address": "172.19.0.1/30", "auto_route": true, "strict_route": false, "sniff": true, "sniff_override_destination": true } ],

试了，一样的，区别不大

**Comment by kay-zhu** [comment]
我总体没有成功，希望大佬能够出一个针对debian的，谢谢

**Comment by mario-huang** [comment]
> 我总体没有成功，希望大佬能够出一个针对debian的，谢谢

目前没有这个计划。debian的包相对较旧，不是作为代理的理想选择。

**Comment by mario-huang** [comment]
@kay-zhu 注意一下DNS的配置，有没有默认走直连。
  "dns": {
    "strategy": "ipv4_only",
    "servers": [
      {
        "tag": "remote",
        "address": "https://1.1.1.1/dns-query",
        "detour": "select"
      },
      {
        "tag": "direct",
        "address": "https://1.12.12.12/dns-query",
        "detour": "direct"
      },
      {
        "tag": "block",
        "address": "rcode://success"
      }
    ],
    "rules": [
      {
        "outbound": "any",
        "server": "direct"
      },
      {
        "clash_mode": "Global",
        "server": "remote"
      },
      {
        "clash_mode": "Direct",
        "server": "direct"
      },
      {
        "rule_set": "geosite-category-ads-all",
        "server": "block"
      },
      {
        "rule_set": [
          "geosite-apple"
        ],
        "server": "direct"
      },
      {
        "rule_set": [
          "geosite-geolocation-!cn",
          "geosite-anthropic"
        ],
        "domain_keyword": [],
        "server": "remote"
      }
    ],
    "final": "direct",    // 默认走直连
    "independent_cache": true
  },

**Comment by kay-zhu** [comment]
"dns": {
    "servers": [
      {
        "tag": "dns_proxy",
        "address": "https://1.1.1.1/dns-query",
        "detour": "🌍 PROXY"
      },
      {
        "tag": "dns_direct",
        "address": "https://223.5.5.5/dns-query",
        "detour": "direct"
      },
      {
        "tag": "dns_block",
        "address": "rcode://success"
      }
    ],
    "rules": [
      {
        "outbound": [
          "any"
        ],
        "server": "dns_direct",
        "rewrite_ttl": 64
      },
      {
        "clash_mode": "direct",
        "server": "dns_direct",
        "rewrite_ttl": 64
      }, 
      {
        "clash_mode": "Global",
        "server": "dns_proxy",
        "rewrite_ttl": 64
      },
      {
        "protocol": [
          "SSH",
          "bittorrent"
        ],
        "server": "dns_direct",
        "rewrite_ttl": 64
      },
      { 
        "domain_suffix": [ 
          "xxx.org" 
        ], 
        "server": "dns_proxy",
        "rewrite_ttl": 64
      },
      {
        "rule_set": [
          "geosite-openai",
          "geosite-bing"
        ],
        "server": "dns_proxy",
        "rewrite_ttl": 64
      }, 
      {
        "rule_set": [
          "geosite-cn"
        ],
        "server": "dns_direct",
        "rewrite_ttl": 64
      }, 
      { 
        "type": "logical", 
        "mode": "and", 
        "rules": [ 
          { 
            "rule_set": "geosite-!cn", 
            "invert": true 
          }, 
          { 
            "rule_set": "geo-cn" 
          } 
        ], 
        "server": "dns_proxy", 
        "client_subnet": "114.114.114.114/24", 
        "rewrite_ttl": 64
      }
    ],
    "final": "dns_proxy",
    "independent_cache": true
  },

**Comment by kay-zhu** [comment]
DNS这里fina改成直连了，入站删掉了dns-in，然后把需要代理的机器DNS指定为公网DNS（119.29.29.29）
修改/etc/nftables.conf，添加以下规则......这里我没添加进旁路由，需要添加吗？（后来我添加了，还是一样的问题存在）

**Comment by kay-zhu** [comment]
final改成直连后，除了代理找不到DNS，连百度都打不开，或很慢很慢，如果加上以下：
{
"type": "direct",
"tag": "dns-in",
"listen": "::",
"listen_port": 53,
"sniff": true
}
然后route的rules加一条：
{
"inbound": "dns-in",
"outbound": "dns-out"
},
百度可以打开，但代理还是不行

**Comment by kay-zhu** [comment]
求教，谢谢
