### ISSUE TITLE
如果使用tproxy的情况

### ISSUE THREAD

**Issue by neomikanagi** [mario-huang/sing-box-bypass-router-transparent-proxy-configuration#2]
请问如果
        "inbounds": [
                {
                        "type": "tproxy",
                        "tag": "tproxy-in",
                        ...
                }
的情况该如何编nft呢？
以及这种情况是否需要设置第一个出站为
                {
                        "type": "direct",
                        "tag": "dns-in",
                        ...
                }
有劳解惑了。

**Comment by mario-huang** [comment]
抱歉我对tproxy并不清楚，不能帮到你了。
